# Generated by Django 5.1 on 2024-09-05 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderEasy_app', '0003_menuitem_cliente_pedido_pedidoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderEasy_app.product'),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
