# Generated by Django 5.1 on 2024-09-05 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderEasy_app', '0004_alter_pedidoitem_menu_item_delete_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoitem',
            old_name='menu_item',
            new_name='product',
        ),
    ]
