# Generated by Django 5.1 on 2024-09-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderEasy_app', '0006_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoitem',
            old_name='product',
            new_name='producto',
        ),
    ]
