# Generated by Django 5.1 on 2024-09-13 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderEasy_app', '0007_rename_product_pedidoitem_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderEasy_app.pedido'),
        ),
    ]
