# Generated by Django 5.1 on 2024-09-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderEasy_app', '0008_alter_pedidoitem_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoitem',
            old_name='producto',
            new_name='product',
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_usuario',
            field=models.CharField(default='User', max_length=150),
            preserve_default=False,
        ),
    ]
