# Generated by Django 5.1 on 2024-09-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderEasy_app', '0009_rename_producto_pedidoitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nombre_usuario',
            field=models.CharField(default='User', max_length=150),
        ),
    ]
