# Generated by Django 5.1 on 2024-09-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderEasy_app', '0010_alter_pedido_nombre_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images', verbose_name='Imagen'),
        ),
    ]
